---
- name: Install mariaDB
  apt:
    name: mariadb-server
    state: present
- name: Update MySQL Configuration file to accept connections from all interfaces
  ini_file:
    path: /etc/mysql/my.cnf
    section: mysqld
    option: bind-address
    value: 0.0.0.0
- name: Start and enable mariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
- name: Configure firewall
  firewalld:
    port: 3306/tcp
    zone: public
    immediate: yes
    permanent: yes
    state: enabled
- name: Install python-mysqldb
  apt:
    name: python3-mysqldb
    state: present